# Generated by Django 5.2.1 on 2025-05-22 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=100)),
                ('card_number', models.CharField(blank=True, max_length=20, null=True)),
                ('expansion', models.CharField(blank=True, max_length=100, null=True)),
                ('rarity', models.CharField(blank=True, max_length=50, null=True)),
                ('illustrator', models.CharField(blank=True, max_length=100, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('card_type', models.CharField(blank=True, max_length=50, null=True)),
                ('special_rule', models.TextField(blank=True, null=True)),
                ('is_ace_spec', models.BooleanField(default=False)),
                ('item_content', models.TextField(blank=True, null=True)),
                ('supporter_content', models.TextField(blank=True, null=True)),
                ('stadium_content', models.TextField(blank=True, null=True)),
                ('tool_content', models.TextField(blank=True, null=True)),
                ('special_energy_content', models.TextField(blank=True, null=True)),
                ('basic_energy', models.CharField(blank=True, max_length=50, null=True)),
                ('supertype', models.CharField(blank=True, max_length=50, null=True)),
                ('hp_num', models.PositiveIntegerField(blank=True, null=True)),
                ('hp_type', models.CharField(blank=True, max_length=50, null=True)),
                ('ability_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ability_content', models.TextField(blank=True, null=True)),
                ('attack_1_name', models.CharField(blank=True, max_length=100, null=True)),
                ('attack_1_points', models.PositiveIntegerField(blank=True, null=True)),
                ('attack_1_energy_cost', models.CharField(blank=True, max_length=100, null=True)),
                ('attack_1_description', models.TextField(blank=True, null=True)),
                ('attack_2_name', models.CharField(blank=True, max_length=100, null=True)),
                ('attack_2_points', models.PositiveIntegerField(blank=True, null=True)),
                ('attack_2_energy_cost', models.CharField(blank=True, max_length=100, null=True)),
                ('attack_2_description', models.TextField(blank=True, null=True)),
                ('weakness_type', models.CharField(blank=True, max_length=50, null=True)),
                ('weakness_calc', models.CharField(blank=True, max_length=20, null=True)),
                ('strength_type', models.CharField(blank=True, max_length=50, null=True)),
                ('strength_calc', models.CharField(blank=True, max_length=20, null=True)),
                ('escape_cost', models.PositiveIntegerField(blank=True, null=True)),
                ('evolution_line', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
