# Generated by Django 5.2.1 on 2025-05-27 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemoncard',
            name='ability_name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
