# Generated by Django 5.2.1 on 2025-05-27 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_pokemoncard_ability_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemoncard',
            name='evolution_line',
            field=models.CharField(blank=True, null=True),
        ),
    ]
